title: Steam URL Opener
description: Opens Steam URLs in your Steam client.
remote_theme: "poole/poole"
baseurl: "https://hdboye.github.io/steam-url-opener/"

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  
sass:
  sass_dir: _sass
  style: :compressed
