name: Node CI

on: [workflow_dispatch]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: 'pack extension dir'
        id: packExtensionDir
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: 'extension'
          zipFilePath: 'build/extension.zip'
      - name: 'build CRX'
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: 'build/redisteam.zip'
          crxFilePath: 'build/redisteam.crx'
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/redisteam.crx
